#Requires -Version 5.1
<#
  generate-browser-config.ps1 - S3 PWA/browser path. Writes
  src/frontend/config.js from config/local.json's PUBLIC values (url +
  anon key - both safe to ship, same values the Electron path already
  exposes via IPC). Never touches or requires a service_role key.

  Usage:
    pwsh tools\generate-browser-config.ps1
#>
$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$configPath = Join-Path $repoRoot 'config\local.json'
$outPath = Join-Path $repoRoot 'src\frontend\config.js'

if (-not (Test-Path -LiteralPath $configPath)) {
  Write-Error "config\local.json not found - copy config\local.example.json and fill in your Supabase project's URL/anon key first."
  exit 1
}

$cfg = Get-Content -LiteralPath $configPath -Raw | ConvertFrom-Json
if (-not $cfg.supabaseUrl -or -not $cfg.supabaseAnonKey) {
  Write-Error "config\local.json is missing supabaseUrl or supabaseAnonKey."
  exit 1
}

$js = @"
// Generated by tools\generate-browser-config.ps1 from config\local.json -
// do not hand-edit, re-run the script instead. See config.example.js for
// why these values (url + anon key) are safe to ship to the browser.
window.TUNA_BROWSER_CONFIG = {
  configured: true,
  url: '$($cfg.supabaseUrl)',
  anonKey: '$($cfg.supabaseAnonKey)',
};
"@

Set-Content -LiteralPath $outPath -Value $js -Encoding utf8
Write-Output "Wrote $outPath"
